In [48]:
#Import libraries
import pandas as pd

In [49]:
# Load datasets
job_df = pd.read_csv("job.csv")
resume_df = pd.read_csv("resume.csv")

In [50]:
job_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22000 entries, 0 to 21999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   country          22000 non-null  object
 1   country_code     22000 non-null  object
 2   date_added       122 non-null    object
 3   has_expired      22000 non-null  object
 4   job_board        22000 non-null  object
 5   job_description  22000 non-null  object
 6   job_title        22000 non-null  object
 7   job_type         20372 non-null  object
 8   location         22000 non-null  object
 9   organization     15133 non-null  object
 10  page_url         22000 non-null  object
 11  salary           3446 non-null   object
 12  sector           16806 non-null  object
 13  uniq_id          22000 non-null  object
dtypes: object(14)
memory usage: 2.3+ MB

In [51]:
resume_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2484 entries, 0 to 2483
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           2484 non-null   int64
 1   Resume_str   2484 non-null   object
 2   Resume_html  2484 non-null   object
 3   Category     2484 non-null   object
dtypes: int64(1), object(3)
memory usage: 77.8+ KB

In [52]:
job_df.head()

,country,country_code,date_added,has_expired,job_board,job_description,job_title,job_type,location,organization,page_url,salary,sector,uniq_id
0,United States of America,US,NaN,No,jobs.monster.com,TeamSoft is seeing an IT Support Specialist to...,IT Support Technician Job in Madison,Full Time Employee,"Madison, WI 53702",NaN,http://jobview.monster.com/it-support-technici...,NaN,IT/Software Development,11d599f229a80023d2f40e7c52cd941e
1,United States of America,US,NaN,No,jobs.monster.com,The Wisconsin State Journal is seeking a flexi...,Business Reporter/Editor Job in Madison,Full Time,"Madison, WI 53708",Printing and Publishing,http://jobview.monster.com/business-reporter-e...,NaN,NaN,e4cbb126dabf22159aff90223243ff2a
2,United States of America,US,NaN,No,jobs.monster.com,Report this job About the Job DePuy Synthes Co...,Johnson & Johnson Family of Companies Job Appl...,"Full Time, Employee",DePuy Synthes Companies is a member of Johnson...,Personal and Household Services,http://jobview.monster.com/senior-training-lea...,NaN,NaN,839106b353877fa3d896ffb9c1fe01c0
3,United States of America,US,NaN,No,jobs.monster.com,Why Join Altec? If you’re considering a career...,Engineer - Quality Job in Dixon,Full Time,"Dixon, CA",Altec Industries,http://jobview.monster.com/engineer-quality-jo...,NaN,Experienced (Non-Manager),58435fcab804439efdcaa7ecca0fd783
4,United States of America,US,NaN,No,jobs.monster.com,Position ID# 76162 # Positions 1 State CT C...,Shift Supervisor - Part-Time Job in Camphill,Full Time Employee,"Camphill, PA",Retail,http://jobview.monster.com/shift-supervisor-pa...,NaN,Project/Program Management,64d0272dc8496abfd9523a8df63c184c

In [53]:
job_df.isnull().sum()

country                0
country_code           0
date_added         21878
has_expired            0
job_board              0
job_description        0
job_title              0
job_type            1628
location               0
organization        6867
page_url               0
salary             18554
sector              5194
uniq_id                0
dtype: int64

In [54]:

resume_df.isnull().sum()

ID             0
Resume_str     0
Resume_html    0
Category       0
dtype: int64

In [55]:
#Remove null values and duplicates
job_df.drop_duplicates(inplace=True)
resume_df.drop_duplicates(inplace=True)
job_df.fillna("", inplace=True)
resume_df.fillna("", inplace=True)

In [56]:
print(job_df.columns)

Index(['country', 'country_code', 'date_added', 'has_expired', 'job_board',
       'job_description', 'job_title', 'job_type', 'location', 'organization',
       'page_url', 'salary', 'sector', 'uniq_id'],
      dtype='object')

In [57]:
job_df.columns.tolist()

['country',
 'country_code',
 'date_added',
 'has_expired',
 'job_board',
 'job_description',
 'job_title',
 'job_type',
 'location',
 'organization',
 'page_url',
 'salary',
 'sector',
 'uniq_id']

In [58]:
job_df["combined_text"] = (
    job_df["job_title"] + " " +
    job_df["job_description"] + " " +
    job_df["sector"] + " " +
    job_df["organization"]
)

In [59]:
print(resume_df.columns)

Index(['ID', 'Resume_str', 'Resume_html', 'Category'], dtype='object')

In [60]:
resume_df["combined_resume"] = resume_df["Resume_str"]

In [61]:
print(job_df[["combined_text"]].head())

print(resume_df[["combined_resume"]].head())

                                       combined_text
0  IT Support Technician Job in Madison TeamSoft ...
1  Business Reporter/Editor Job in Madison The Wi...
2  Johnson & Johnson Family of Companies Job Appl...
3  Engineer - Quality Job in Dixon Why Join Altec...
4  Shift Supervisor - Part-Time Job in Camphill P...
                                     combined_resume
0           HR ADMINISTRATOR/MARKETING ASSOCIATE\...
1           HR SPECIALIST, US HR OPERATIONS      ...
2           HR DIRECTOR       Summary      Over 2...
3           HR SPECIALIST       Summary    Dedica...
4           HR MANAGER         Skill Highlights  ...

In [62]:
job_df.sample(1000, random_state=42).to_csv(
    "clean_job_small.csv",
    index=False
)

resume_df.sample(200, random_state=42).to_csv(
    "clean_resume_small.csv",
    index=False
)

In [63]:
job_df

,country,country_code,date_added,has_expired,job_board,job_description,job_title,job_type,location,organization,page_url,salary,sector,uniq_id,combined_text
0,United States of America,US,,No,jobs.monster.com,TeamSoft is seeing an IT Support Specialist to...,IT Support Technician Job in Madison,Full Time Employee,"Madison, WI 53702",,http://jobview.monster.com/it-support-technici...,,IT/Software Development,11d599f229a80023d2f40e7c52cd941e,IT Support Technician Job in Madison TeamSoft ...
1,United States of America,US,,No,jobs.monster.com,The Wisconsin State Journal is seeking a flexi...,Business Reporter/Editor Job in Madison,Full Time,"Madison, WI 53708",Printing and Publishing,http://jobview.monster.com/business-reporter-e...,,,e4cbb126dabf22159aff90223243ff2a,Business Reporter/Editor Job in Madison The Wi...
2,United States of America,US,,No,jobs.monster.com,Report this job About the Job DePuy Synthes Co...,Johnson & Johnson Family of Companies Job Appl...,"Full Time, Employee",DePuy Synthes Companies is a member of Johnson...,Personal and Household Services,http://jobview.monster.com/senior-training-lea...,,,839106b353877fa3d896ffb9c1fe01c0,Johnson & Johnson Family of Companies Job Appl...
3,United States of America,US,,No,jobs.monster.com,Why Join Altec? If you’re considering a career...,Engineer - Quality Job in Dixon,Full Time,"Dixon, CA",Altec Industries,http://jobview.monster.com/engineer-quality-jo...,,Experienced (Non-Manager),58435fcab804439efdcaa7ecca0fd783,Engineer - Quality Job in Dixon Why Join Altec...
4,United States of America,US,,No,jobs.monster.com,Position ID# 76162 # Positions 1 State CT C...,Shift Supervisor - Part-Time Job in Camphill,Full Time Employee,"Camphill, PA",Retail,http://jobview.monster.com/shift-supervisor-pa...,,Project/Program Management,64d0272dc8496abfd9523a8df63c184c,Shift Supervisor - Part-Time Job in Camphill P...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21995,United States of America,US,,No,jobs.monster.com,This is a major premier Cincinnati based finan...,Assistant Vice President - Controller Job in C...,Full Time,"Cincinnati, OH",,http://jobview.monster.com/Assistant-Vice-Pres...,"120,000.00 - 160,000.00 $ /yearbonus",,a80bc8cc3a90c17eef418963803bc640,Assistant Vice President - Controller Job in C...
21996,United States of America,US,,No,jobs.monster.com,Luxury homebuilder in Cincinnati seeking multi...,Accountant Job in Cincinnati,Full Time,"Cincinnati, OH 45236",Construction - Residential & Commercial/Office,http://jobview.monster.com/Accountant-Job-Cinc...,"45,000.00 - 60,000.00 $ /year",Manager (Manager/Supervisor of Staff),419a3714be2b30a10f628de207d041de,Accountant Job in Cincinnati Luxury homebuilde...
21997,United States of America,US,,No,jobs.monster.com,RE: Adobe AEM- Client - Loca...,AEM/CQ developer Job in Chicago,Full Time,"Chicago, IL 60602",,http://jobview.monster.com/AEM-CQ5-developer-J...,,,5a590350b73b2cec46b05750a208e345,AEM/CQ developer Job in Chicago RE: Adobe AEM-...
21998,United States of America,US,,No,jobs.monster.com,Jernberg Industries was established in 1937 an...,Electrician - Experienced Forging Electrician ...,Full Time Employee,"Chicago, IL 60609","Jernberg Industries, Inc.",http://jobview.monster.com/Electrician-Experie...,25.00 - 28.00 $ /hour,Installation/Maintenance/Repair,40161cf61c283af9dc2b0a62947a5f1b,Electrician - Experienced Forging Electrician ...
21999,United States of America,US,,No,jobs.monster.com,Contract AdministratorCan you be the point per...,Contract Administrator Job in Cincinnati,Full Time,"Cincinnati, OH",,http://jobview.monster.com/Contract-Administra...,"40,000.00 - 46,000.00 $ /year+ annual bonus (u...",Experienced (Non-Manager),cb49f16ad72627b109e434e0cac97f7a,Contract Administrator Job in Cincinnati Contr...

In [64]:
import os

print(os.listdir())

['.ipynb_checkpoints', 'app.py', 'clean_jobs.csv', 'clean_jobs_small.csv', 'clean_job_small.csv', 'clean_resume.csv', 'clean_resume_small.csv', 'data preprocessing.ipynb', 'implementation.ipynb', 'Job-Recommendation-System', 'job.csv', 'requirements.txt', 'Resume.csv']

In [65]:
import os

print("clean_job_small.csv:",
      round(os.path.getsize("clean_job_small.csv") / 1024 / 1024, 2),
      "MB")

print("clean_resume_small.csv:",
      round(os.path.getsize("clean_resume_small.csv") / 1024 / 1024, 2),
      "MB")

clean_job_small.csv: 5.55 MB
clean_resume_small.csv: 5.67 MB